### ISSUE TITLE
Error with step as of 1.1.1

### ISSUE THREAD

**Issue by ltsuchiya** [bitrise-steplib/steps-export-xcarchive-mac#13] opened 2022-02-11 02:47 UTC
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.1.1.
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

After using this step for over a year we noticed recently that our MacCatalyst builds started to break with this message:

<img width="653" alt="Screen Shot 2022-02-10 at 6 40 24 PM" src="https://user-images.githubusercontent.com/29567184/153529846-03f97b1e-d343-4cc0-9a0c-937bdd40c30a.png">

I noticed that this workflow step was updated within the past week so I tried reverting to an older step 1.0.4 -- in which the build succeeded.

I'd like to figure out if this is something on our end or an actual issue with the most recent 1.1.1 version. I've added bitrise support to the app, what other type of information would be useful to help figure this out?

### Bitrise info

- Build URL: https://app.bitrise.io/build/0b38cadd-c487-4e60-8c19-4fb5a29705a9#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES 
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by Vincent-Loi** [comment] 2022-02-11 12:59
Happening on our end too

**Comment by ofalvai** [comment] 2022-03-03 12:33
Hello @ltsuchiya, @Vincent-Loi 👋 

We are sorry about the issue, please upgrade to the [latest version](https://github.com/bitrise-steplib/steps-export-xcarchive-mac/releases/1.1.2) where the issue is now fixed.

**Closed as completed by ofalvai** 2022-03-03 12:33 UTC
